language: java
jdk:
  - openjdk11

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull openjdk:11-jre-slim-sid

script:
  - cd baeldung-ci-cd-process && ./mvnw clean install
  - cd baeldung-ci-cd-process && ./mvnw deploy jib:build -P deploy-docker
  
